# Generated by Django 4.1.7 on 2023-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_opportunity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='created_by',
            new_name='converted_by',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expected_turnover',
            field=models.IntegerField(default=0),
        ),
    ]
