# Generated by Django 4.1.7 on 2023-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_created_by_opportunity_converted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('WIN', 'Win'), ('LOST', 'Lost'), ('IN_PROCESS', 'In process'), ('OPEN', 'Open')], default='Open', max_length=10),
        ),
    ]
