# Generated by Django 4.1.7 on 2023-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_opportunity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WIN', 'Win'), ('LOST', 'Lost'), ('IN_PROCESS', 'In process')], default='Open', max_length=10),
        ),
    ]
