# Generated by Django 4.1.7 on 2023-04-12 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_opportunity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=33, unique=True)),
                ('new_name', models.CharField(max_length=33, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 4, 12, 16, 37, 35, 905201))),
            ],
        ),
    ]
