# Generated by Django 4.1.7 on 2023-03-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.manager'),
        ),
    ]
