# Generated by Django 4.1.7 on 2023-03-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_salesman_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.generalmanager'),
        ),
    ]
