# Generated by Django 4.1.7 on 2023-03-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_manager_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='manager',
            new_name='general_manager',
        ),
    ]
